name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: mkdir build && cd build &&
          cmake -DCMAKE_CXX_COMPILER=g++-10
          -DCMAKE_BUILD_TYPE=Debug
          -DTERMCONTROL_BUILD_TESTS=ON .. .
      - name: Build tests
        run: cmake --build build
      - name: Run tests
        run: cd build && ctest